name: AMI Copy Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:
    inputs:
      TOOLKIT_VERSION:
        description: 'Version of the Ansible Automation Toolkit'
        required: true
        default: 'default'
      REGION:
        description: 'AWS region for copy to (e.g., us-west-2)'
        required: true
        default: 'us-west-2'
      SOURCE_REGION:
        description: 'AWS region from AMIs copied (e.g., eu-central-1)'
        required: true
        default: 'eu-central-1'
      SOURCE_ACCOUNT_ID:
        description: 'AWS account ID from AMIs copied (optional)'
        required: false
        default: '339712742264'

permissions:
  id-token: write
  contents: read

jobs:
  ami_copy:
    uses: inqwise/ansible-automation-toolkit/.github/workflows/ami-copy-shared.yml@default
    with:
      ROLE: "arn:aws:iam::208940048781:role/aws-mastermind-workflow-role"
      TOOLKIT_VERSION: ${{ inputs.TOOLKIT_VERSION || 'default' }}
      REGION: ${{ inputs.REGION || 'us-west-2' }}
      SOURCE_REGION: ${{ inputs.SOURCE_REGION || 'eu-central-1' }}
      SOURCE_ACCOUNT_ID: ${{ inputs.SOURCE_ACCOUNT_ID || '339712742264' }}