name: AMI Assign Template Workflow

on:
  schedule:
    - cron: '10,20 0 * * *'  # Runs daily at 00:10 and 00:20 UTC
  workflow_dispatch:
    inputs:
      TOOLKIT_VERSION:
        description: 'Version of the Ansible Automation Toolkit'
        required: false
        default: 'default'
      REGION:
        description: 'AWS region for assignment (e.g., us-west-2)'
        required: false
        default: 'us-west-2'
      MAKE_DEFAULT_VERSION:
        description: 'Make Default Version (true/false)'
        required: false
        default: 'true'

permissions:
  id-token: write
  contents: read

jobs:
  ami_assign:
    uses: inqwise/ansible-automation-toolkit/.github/workflows/ami-assign-template.yml@default
    with:
      ROLE: "arn:aws:iam::208940048781:role/aws-mastermind-workflow-role"
      TOOLKIT_VERSION: ${{ inputs.TOOLKIT_VERSION || 'default' }}
      REGION: ${{ inputs.REGION || 'us-west-2' }}
      MAKE_DEFAULT_VERSION: ${{ inputs.MAKE_DEFAULT_VERSION || 'true' }}